/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JOptionPane;

/**
 *
 * @author Kaua
 */
public class Cadastro_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro_GUI
     */
    public Cadastro_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cadastrar_BTN = new javax.swing.JButton();
        login_BTN = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        nome_txt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cpf_txt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tel_txt = new javax.swing.JTextField();
        email_txt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        senha_txt = new javax.swing.JTextField();
        cadastro_BTN = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        fzlogin_BTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setForeground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/os p (3).png"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(-480, -90, 920, 700);

        cadastrar_BTN.setBackground(new java.awt.Color(255, 255, 0));
        cadastrar_BTN.setForeground(new java.awt.Color(0, 0, 0));
        cadastrar_BTN.setText("CADASTRAR");
        cadastrar_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrar_BTNActionPerformed(evt);
            }
        });
        jPanel2.add(cadastrar_BTN);
        cadastrar_BTN.setBounds(530, 490, 160, 50);

        login_BTN.setBackground(new java.awt.Color(0, 0, 0));
        login_BTN.setForeground(new java.awt.Color(255, 255, 255));
        login_BTN.setText("LOGIN");
        login_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_BTNActionPerformed(evt);
            }
        });
        jPanel2.add(login_BTN);
        login_BTN.setBounds(450, 0, 160, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/perfil.png"))); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(440, 70, 70, 60);
        jPanel2.add(nome_txt);
        nome_txt.setBounds(510, 90, 190, 30);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nome Completo");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(510, 70, 130, 16);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cpf_icon.png"))); // NOI18N
        jPanel2.add(jLabel4);
        jLabel4.setBounds(450, 140, 70, 60);
        jPanel2.add(cpf_txt);
        cpf_txt.setBounds(510, 160, 190, 30);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CPF");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(510, 140, 130, 16);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Telefone");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(510, 220, 130, 16);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icon_tel.png"))); // NOI18N
        jPanel2.add(jLabel7);
        jLabel7.setBounds(450, 220, 70, 70);
        jPanel2.add(tel_txt);
        tel_txt.setBounds(510, 240, 190, 30);
        jPanel2.add(email_txt);
        email_txt.setBounds(510, 320, 190, 30);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("E-mail");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(510, 300, 130, 16);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/email1.png"))); // NOI18N
        jPanel2.add(jLabel9);
        jLabel9.setBounds(450, 300, 60, 60);

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Senha");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(510, 380, 130, 16);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/password.png"))); // NOI18N
        jPanel2.add(jLabel11);
        jLabel11.setBounds(450, 390, 70, 60);
        jPanel2.add(senha_txt);
        senha_txt.setBounds(510, 400, 190, 30);

        cadastro_BTN.setBackground(new java.awt.Color(255, 255, 0));
        cadastro_BTN.setForeground(new java.awt.Color(0, 0, 0));
        cadastro_BTN.setText("CADASTRO");
        cadastro_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastro_BTNActionPerformed(evt);
            }
        });
        jPanel2.add(cadastro_BTN);
        cadastro_BTN.setBounds(600, 0, 160, 50);

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Já tem conta?");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(520, 450, 90, 16);

        fzlogin_BTN.setForeground(new java.awt.Color(0, 51, 204));
        fzlogin_BTN.setText("Fazer Login");
        fzlogin_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fzlogin_BTNActionPerformed(evt);
            }
        });
        jPanel2.add(fzlogin_BTN);
        fzlogin_BTN.setBounds(600, 450, 110, 20);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 760, 550);

        setSize(new java.awt.Dimension(763, 546));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrar_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrar_BTNActionPerformed
JOptionPane.showMessageDialog(null,"Cadastro feito com sucesso");
        new Login_GUI().setVisible(true);
    }//GEN-LAST:event_cadastrar_BTNActionPerformed

    private void login_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_BTNActionPerformed
       new Login_GUI().setVisible(true);
    }//GEN-LAST:event_login_BTNActionPerformed

    private void cadastro_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastro_BTNActionPerformed
       new Cadastro_GUI().setVisible(true);
    }//GEN-LAST:event_cadastro_BTNActionPerformed

    private void fzlogin_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fzlogin_BTNActionPerformed
        new Login_GUI().setVisible(true);
    }//GEN-LAST:event_fzlogin_BTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrar_BTN;
    private javax.swing.JButton cadastro_BTN;
    private javax.swing.JTextField cpf_txt;
    private javax.swing.JTextField email_txt;
    private javax.swing.JButton fzlogin_BTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton login_BTN;
    private javax.swing.JTextField nome_txt;
    private javax.swing.JTextField senha_txt;
    private javax.swing.JTextField tel_txt;
    // End of variables declaration//GEN-END:variables
}
