/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Venda_DAO;
import Model.Item_Venda;
import Model.Produto;
import Model.Venda;
import java.awt.Color;
import java.awt.Component;
import java.awt.Graphics;
import javax.swing.JComponent;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.MenuElement;
import javax.swing.plaf.basic.BasicMenuBarUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Kaua
 */
public class Caixa_GUI extends javax.swing.JFrame {
    
    private void customizeMenuBar(JMenuBar menuBar) {

        menuBar.setUI(new BasicMenuBarUI() {

            @Override
            public void paint(Graphics g, JComponent c) {
                g.setColor(Color.black);
                g.fillRect(0, 0, c.getWidth(), c.getHeight());
            }

        });

        MenuElement[] menus = menuBar.getSubElements();

        for (MenuElement menuElement : menus) {

            JMenu menu = (JMenu) menuElement.getComponent();
            changeComponentColors(menu);
            menu.setOpaque(true);

            MenuElement[] menuElements = menu.getSubElements();

            for (MenuElement popupMenuElement : menuElements) {

                JPopupMenu popupMenu = (JPopupMenu) popupMenuElement.getComponent();
                popupMenu.setBorder(null);

                MenuElement[] menuItens = popupMenuElement.getSubElements();

                for (MenuElement menuItemElement : menuItens) {

                    JMenuItem menuItem = (JMenuItem) menuItemElement.getComponent();
                    changeComponentColors(menuItem);
                    menuItem.setOpaque(true);

                }
            }
        }
    }

    private void changeComponentColors(Component comp) {
        comp.setBackground(Color.black);
        comp.setForeground(Color.white);
    }

    public void readJTable() {
        DefaultTableModel modelo = (DefaultTableModel) item_table.getModel();
        Venda_DAO pdao = new Venda_DAO();

      
    }

    /**
     * Creates new form Caixa_GUI
     */
    public Caixa_GUI() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) item_table.getModel();
        item_table.setRowSorter(new TableRowSorter(modelo));
        item_table.setAutoCreateRowSorter(false);
        readJTable();
        customizeMenuBar(barrinha);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        preco_txt = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cpf_text = new javax.swing.JLabel();
        nome_text = new javax.swing.JLabel();
        valortl_txt = new javax.swing.JTextField();
        finalizar_BTN = new javax.swing.JButton();
        totalizar_BTN = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        item_table = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        editar_BTN = new javax.swing.JButton();
        excluir_BTN = new javax.swing.JButton();
        add_BTN = new javax.swing.JButton();
        buscar_BTN = new javax.swing.JButton();
        limpar_BTN = new javax.swing.JButton();
        limpar_BTN1 = new javax.swing.JButton();
        Id_venda_txt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        nomepdt_txt1 = new javax.swing.JLabel();
        buscar_txt6 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        buscar_txt7 = new javax.swing.JTextField();
        barrinha = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        preco_txt.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        preco_txt.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(preco_txt);
        preco_txt.setBounds(130, 160, 120, 40);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Preço :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(70, 160, 60, 40);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Id_Venda :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(70, 250, 100, 30);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Dados da Venda :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(70, 20, 150, 40);

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Valor Total:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(270, 420, 120, 50);
        jPanel1.add(cpf_text);
        cpf_text.setBounds(580, 150, 160, 30);
        jPanel1.add(nome_text);
        nome_text.setBounds(580, 110, 160, 30);
        jPanel1.add(valortl_txt);
        valortl_txt.setBounds(360, 430, 80, 30);

        finalizar_BTN.setBackground(new java.awt.Color(255, 255, 51));
        finalizar_BTN.setForeground(new java.awt.Color(0, 0, 0));
        finalizar_BTN.setText("FINALIZAR");
        jPanel1.add(finalizar_BTN);
        finalizar_BTN.setBounds(640, 430, 160, 40);

        totalizar_BTN.setBackground(new java.awt.Color(255, 255, 51));
        totalizar_BTN.setForeground(new java.awt.Color(0, 0, 0));
        totalizar_BTN.setText("Totalizar");
        jPanel1.add(totalizar_BTN);
        totalizar_BTN.setBounds(40, 430, 160, 40);

        jScrollPane1.setBackground(new java.awt.Color(103, 103, 103));
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

        item_table.setAutoCreateRowSorter(true);
        item_table.setBackground(new java.awt.Color(103, 103, 103));
        item_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Produto", "Preço", "Quantidade", "Id Venda"
            }
        ));
        jScrollPane1.setViewportView(item_table);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 300, 880, 230);

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Id_Produto :");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(70, 80, 100, 40);

        editar_BTN.setBackground(new java.awt.Color(37, 36, 36));
        editar_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/editar (1).png"))); // NOI18N
        editar_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editar_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(editar_BTN);
        editar_BTN.setBounds(570, 210, 60, 50);

        excluir_BTN.setBackground(new java.awt.Color(37, 36, 36));
        excluir_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/excluir (2).png"))); // NOI18N
        jPanel1.add(excluir_BTN);
        excluir_BTN.setBounds(650, 210, 60, 50);

        add_BTN.setBackground(new java.awt.Color(37, 36, 36));
        add_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/adicionar (2).png"))); // NOI18N
        add_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(add_BTN);
        add_BTN.setBounds(490, 210, 54, 50);

        buscar_BTN.setBackground(new java.awt.Color(37, 36, 36));
        buscar_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lupa (1).png"))); // NOI18N
        buscar_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscar_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(buscar_BTN);
        buscar_BTN.setBounds(240, 90, 60, 30);

        limpar_BTN.setBackground(new java.awt.Color(255, 255, 51));
        limpar_BTN.setForeground(new java.awt.Color(0, 0, 0));
        limpar_BTN.setText("Abrir Nova Venda");
        limpar_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpar_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(limpar_BTN);
        limpar_BTN.setBounds(470, 90, 150, 32);

        limpar_BTN1.setBackground(new java.awt.Color(255, 255, 51));
        limpar_BTN1.setForeground(new java.awt.Color(0, 0, 0));
        limpar_BTN1.setText("Limpar");
        limpar_BTN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpar_BTN1ActionPerformed(evt);
            }
        });
        jPanel1.add(limpar_BTN1);
        limpar_BTN1.setBounds(710, 90, 110, 32);
        jPanel1.add(Id_venda_txt);
        Id_venda_txt.setBounds(160, 250, 60, 30);

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Nome_Produto :");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(70, 120, 120, 40);

        nomepdt_txt1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        nomepdt_txt1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(nomepdt_txt1);
        nomepdt_txt1.setBounds(190, 120, 120, 40);
        jPanel1.add(buscar_txt6);
        buscar_txt6.setBounds(160, 90, 60, 30);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Quantidade :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(70, 200, 100, 40);
        jPanel1.add(buscar_txt7);
        buscar_txt7.setBounds(170, 210, 60, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 880, 500);

        barrinha.setBackground(new java.awt.Color(0, 0, 0));
        barrinha.setForeground(new java.awt.Color(255, 255, 255));

        jMenu1.setBackground(new java.awt.Color(0, 0, 0));
        jMenu1.setForeground(new java.awt.Color(255, 255, 255));
        jMenu1.setText("Início");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem2.setText("Tela Inicial");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        barrinha.add(jMenu1);

        jMenu2.setBackground(new java.awt.Color(0, 0, 0));
        jMenu2.setForeground(new java.awt.Color(255, 255, 255));
        jMenu2.setText("Produtos");

        jMenuItem3.setText("Produtos");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        barrinha.add(jMenu2);

        jMenu3.setBackground(new java.awt.Color(0, 0, 0));
        jMenu3.setForeground(new java.awt.Color(255, 255, 255));
        jMenu3.setText("Caixa");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        jMenuItem4.setText("Caixa");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        barrinha.add(jMenu3);

        jMenu4.setBackground(new java.awt.Color(0, 0, 0));
        jMenu4.setForeground(new java.awt.Color(255, 255, 255));
        jMenu4.setText("Vendas");
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });

        jMenuItem6.setText("Vendas");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem6);

        barrinha.add(jMenu4);

        jMenu8.setBackground(new java.awt.Color(0, 0, 0));
        jMenu8.setForeground(new java.awt.Color(255, 255, 255));
        jMenu8.setText("Sair");
        jMenu8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu8ActionPerformed(evt);
            }
        });

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        jMenuItem1.setText("Fechar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem1);

        barrinha.add(jMenu8);

        setJMenuBar(barrinha);

        setSize(new java.awt.Dimension(877, 526));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void editar_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editar_BTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editar_BTNActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        new Inicio_GUI().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        new Produtos_GUI().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        new Caixa_GUI().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        new Vendas_GUI().setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed

    }//GEN-LAST:event_jMenu4ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:

        String x =  JOptionPane.showInputDialog(null, "Deseja realmente fechar ?"
            + " \n1 - Sim"
            + " \n2 - Não "
        );
        int op = Integer.parseInt(x);

        if(op == 1){
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenu8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu8ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenu8ActionPerformed

    private void add_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_BTNActionPerformed
        // TODO add your handling code here:
        Item_Venda v = new Item_Venda();
        Venda_DAO dao = new Venda_DAO();
        v.setVen_id(Integer.parseInt(Id_venda_txt.getText()));
        v.setPdt_id(Integer.parseInt(buscar_txt6.getText()));
        v.setQuantidade(Integer.parseInt(buscar_txt7.getText()));
//        p.setTipo(tipopdt_cmb.getSelectedItem().toString().toLowerCase());
        dao.inserir_item(v);
        readJTable();
        Id_venda_txt.setText("");
        nomepdt_txt1.setText("");
        preco_txt.setText("");
        buscar_txt7.setText("");
        buscar_txt7.setText("");
        

//        p.setTipo(tipopdt_cmb.getSelectedItem().toString().toLowerCase());
  
        dao.read(v);
    }//GEN-LAST:event_add_BTNActionPerformed

    private void buscar_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscar_BTNActionPerformed
        // TODO add your handling code here:
        Produto p = new Produto();
        Venda_DAO dao = new Venda_DAO();
        p.setId(Integer.parseInt(buscar_txt6.getText()));
//        p.setTipo(tipopdt_cmb.getSelectedItem().toString().toLowerCase());
        dao.consultar(p);
        readJTable();
    }//GEN-LAST:event_buscar_BTNActionPerformed

    private void limpar_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpar_BTNActionPerformed
        // TODO add your handling code here:
        new ddscliente_GUI().setVisible(true);
    }//GEN-LAST:event_limpar_BTNActionPerformed

    private void limpar_BTN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpar_BTN1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_limpar_BTN1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Caixa_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Caixa_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Caixa_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Caixa_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Caixa_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField Id_venda_txt;
    private javax.swing.JButton add_BTN;
    public static javax.swing.JMenuBar barrinha;
    private javax.swing.JButton buscar_BTN;
    public static javax.swing.JTextField buscar_txt6;
    private javax.swing.JTextField buscar_txt7;
    private javax.swing.JLabel cpf_text;
    private javax.swing.JButton editar_BTN;
    private javax.swing.JButton excluir_BTN;
    private javax.swing.JButton finalizar_BTN;
    public static javax.swing.JTable item_table;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton limpar_BTN;
    private javax.swing.JButton limpar_BTN1;
    private javax.swing.JLabel nome_text;
    public static javax.swing.JLabel nomepdt_txt1;
    public static javax.swing.JLabel preco_txt;
    private javax.swing.JButton totalizar_BTN;
    private javax.swing.JTextField valortl_txt;
    // End of variables declaration//GEN-END:variables
}
