/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Produto_DAO;
import Model.Produto;
import java.awt.Color;
import java.awt.Component;
import java.awt.Graphics;
import javax.swing.JComponent;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.MenuElement;
import javax.swing.plaf.basic.BasicMenuBarUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Kaua
 */
public class Produtos_GUI extends javax.swing.JFrame {

    private void customizeMenuBar(JMenuBar menuBar) {

        menuBar.setUI(new BasicMenuBarUI() {

            @Override
            public void paint(Graphics g, JComponent c) {
                g.setColor(Color.black);
                g.fillRect(0, 0, c.getWidth(), c.getHeight());
            }

        });

        MenuElement[] menus = menuBar.getSubElements();

        for (MenuElement menuElement : menus) {

            JMenu menu = (JMenu) menuElement.getComponent();
            changeComponentColors(menu);
            menu.setOpaque(true);

            MenuElement[] menuElements = menu.getSubElements();

            for (MenuElement popupMenuElement : menuElements) {

                JPopupMenu popupMenu = (JPopupMenu) popupMenuElement.getComponent();
                popupMenu.setBorder(null);

                MenuElement[] menuItens = popupMenuElement.getSubElements();

                for (MenuElement menuItemElement : menuItens) {

                    JMenuItem menuItem = (JMenuItem) menuItemElement.getComponent();
                    changeComponentColors(menuItem);
                    menuItem.setOpaque(true);

                }
            }
        }
    }

    private void changeComponentColors(Component comp) {
        comp.setBackground(Color.black);
        comp.setForeground(Color.white);
    }

    public void readJTable() {
        DefaultTableModel modelo = (DefaultTableModel) produtos_table.getModel();
        Produto_DAO pdao = new Produto_DAO();

        modelo.setNumRows(0);
        for (Produto p : pdao.read()) {
            modelo.addRow(new Object[]{
                p.getId(),
                p.getNome(),
                p.getPreco(),
                p.getTipo()
            });
        }
    }

    /**
     * Creates new form Produtos_GUI
     */
    public Produtos_GUI() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) produtos_table.getModel();
        produtos_table.setRowSorter(new TableRowSorter(modelo));
        produtos_table.setAutoCreateRowSorter(false);
        readJTable();
        customizeMenuBar(barrinha);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        preco_txt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tipo_txt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        nomepro_txt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        id_txt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        produtos_table = new javax.swing.JTable();
        limpar_BTN = new javax.swing.JButton();
        buscar_BTN = new javax.swing.JButton();
        editar_BTN = new javax.swing.JButton();
        excluir_BTN = new javax.swing.JButton();
        add_BTN = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        barrinha = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Preço:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(480, 60, 60, 20);

        preco_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preco_txtActionPerformed(evt);
            }
        });
        jPanel1.add(preco_txt);
        preco_txt.setBounds(540, 60, 80, 24);

        jLabel3.setBackground(new java.awt.Color(103, 103, 103));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Para adicionar um novo produto");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(240, 130, 250, 40);

        tipo_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipo_txtActionPerformed(evt);
            }
        });
        jPanel1.add(tipo_txt);
        tipo_txt.setBounds(90, 160, 100, 24);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nome:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(230, 60, 60, 20);

        nomepro_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomepro_txtActionPerformed(evt);
            }
        });
        jPanel1.add(nomepro_txt);
        nomepro_txt.setBounds(280, 60, 150, 24);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Id Produto:  ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 60, 100, 20);
        jPanel1.add(id_txt);
        id_txt.setBounds(110, 60, 90, 24);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tipo:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(40, 160, 100, 20);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("não é necesssário inserir um id!");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(240, 150, 260, 40);

        produtos_table.setBackground(new java.awt.Color(103, 103, 103));
        produtos_table.setForeground(new java.awt.Color(255, 255, 255));
        produtos_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Tipo", "Preço"
            }
        ));
        produtos_table.setToolTipText("");
        produtos_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                produtos_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(produtos_table);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 240, 880, 270);

        limpar_BTN.setBackground(new java.awt.Color(255, 255, 51));
        limpar_BTN.setForeground(new java.awt.Color(0, 0, 0));
        limpar_BTN.setText("Limpar");
        limpar_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpar_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(limpar_BTN);
        limpar_BTN.setBounds(720, 60, 110, 40);

        buscar_BTN.setBackground(new java.awt.Color(37, 36, 36));
        buscar_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lupa (1).png"))); // NOI18N
        buscar_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscar_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(buscar_BTN);
        buscar_BTN.setBounds(610, 160, 68, 50);

        editar_BTN.setBackground(new java.awt.Color(37, 36, 36));
        editar_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/editar (1).png"))); // NOI18N
        editar_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editar_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(editar_BTN);
        editar_BTN.setBounds(700, 160, 67, 50);

        excluir_BTN.setBackground(new java.awt.Color(37, 36, 36));
        excluir_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/excluir (2).png"))); // NOI18N
        excluir_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluir_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(excluir_BTN);
        excluir_BTN.setBounds(790, 160, 60, 50);

        add_BTN.setBackground(new java.awt.Color(37, 36, 36));
        add_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/adicionar (2).png"))); // NOI18N
        add_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(add_BTN);
        add_BTN.setBounds(520, 160, 54, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pri_fundo.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 880, 480);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 890, 510);

        barrinha.setBackground(new java.awt.Color(0, 0, 0));

        jMenu1.setBackground(new java.awt.Color(0, 0, 0));
        jMenu1.setForeground(new java.awt.Color(255, 255, 255));
        jMenu1.setText("Início");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem2.setText("Tela Inicial");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        barrinha.add(jMenu1);

        jMenu2.setBackground(new java.awt.Color(0, 0, 0));
        jMenu2.setForeground(new java.awt.Color(255, 255, 255));
        jMenu2.setText("Produtos");

        jMenuItem3.setText("Produtos");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        barrinha.add(jMenu2);

        jMenu3.setBackground(new java.awt.Color(0, 0, 0));
        jMenu3.setForeground(new java.awt.Color(255, 255, 255));
        jMenu3.setText("Caixa");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        jMenuItem4.setText("Caixa");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        barrinha.add(jMenu3);

        jMenu4.setBackground(new java.awt.Color(0, 0, 0));
        jMenu4.setForeground(new java.awt.Color(255, 255, 255));
        jMenu4.setText("Vendas");
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });

        jMenuItem6.setText("Vendas");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem6);

        barrinha.add(jMenu4);

        jMenu8.setBackground(new java.awt.Color(0, 0, 0));
        jMenu8.setForeground(new java.awt.Color(255, 255, 255));
        jMenu8.setText("Sair");
        jMenu8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu8ActionPerformed(evt);
            }
        });

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        jMenuItem1.setText("Fechar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem1);

        barrinha.add(jMenu8);

        setJMenuBar(barrinha);

        setSize(new java.awt.Dimension(877, 526));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void preco_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preco_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_preco_txtActionPerformed

    private void nomepro_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomepro_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomepro_txtActionPerformed

    private void tipo_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipo_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipo_txtActionPerformed

    private void limpar_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpar_BTNActionPerformed
        // TODO add your handling code here:
        id_txt.setText("");
        nomepro_txt.setText("");
        preco_txt.setText("");
        tipo_txt.setText("");
    }//GEN-LAST:event_limpar_BTNActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        new Inicio_GUI().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        new Produtos_GUI().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        new Caixa_GUI().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        new Vendas_GUI().setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed

    }//GEN-LAST:event_jMenu4ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:

        String x = JOptionPane.showInputDialog(null, "Deseja realmente fechar ?"
                + " \n1 - Sim"
                + " \n2 - Não "
        );
        int op = Integer.parseInt(x);

        if (op == 1) {
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenu8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu8ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenu8ActionPerformed

    private void add_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_BTNActionPerformed
        // TODO add your handling code here:
        String preco = preco_txt.getText();
        preco = preco.replace(",", ".");
        Produto p = new Produto();
        Produto_DAO dao = new Produto_DAO();
        p.setNome(nomepro_txt.getText());
        p.setPreco(Double.parseDouble(preco));
        p.setTipo(tipo_txt.getText());
        dao.create(p);
        readJTable();
        id_txt.setText("");
        nomepro_txt.setText("");
        preco_txt.setText("");
        tipo_txt.setText("");
    }//GEN-LAST:event_add_BTNActionPerformed

    private void buscar_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscar_BTNActionPerformed
        // TODO add your handling code here:
        Produto p = new Produto();
        Produto_DAO dao = new Produto_DAO();
        p.setId(Integer.parseInt(id_txt.getText()));
        dao.consul(p);
        readJTable();
    }//GEN-LAST:event_buscar_BTNActionPerformed

    private void editar_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editar_BTNActionPerformed
        // TODO add your handling code here:
        Produto p = new Produto();
        Produto_DAO dao = new Produto_DAO();
        p.setNome(nomepro_txt.getText());
        p.setPreco(Double.parseDouble(preco_txt.getText()));
        p.setTipo(tipo_txt.getText());
        p.setId(Integer.parseInt(id_txt.getText()));
//        p.setTipo(tipopdt_cmb.getSelectedItem().toString().toLowerCase());
        dao.update(p);
        id_txt.setText("");
        nomepro_txt.setText("");
        preco_txt.setText("");
        tipo_txt.setText("");
        readJTable();
    }//GEN-LAST:event_editar_BTNActionPerformed

    private void excluir_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluir_BTNActionPerformed
        // TODO add your handling code here:
         Produto p = new Produto();
        Produto_DAO dao = new Produto_DAO();
        p.setId(Integer.parseInt(id_txt.getText()));
//        p.setTipo(tipopdt_cmb.getSelectedItem().toString().toLowerCase());
        dao.delete(p);
        readJTable();
        id_txt.setText("");
        nomepro_txt.setText("");
        preco_txt.setText("");
        tipo_txt.setText("");
    }//GEN-LAST:event_excluir_BTNActionPerformed

    private void produtos_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_produtos_tableMouseClicked
        // TODO add your handling code here:
        if (produtos_table.getSelectedRow() != -1) {
            id_txt.setText(produtos_table.getValueAt(produtos_table.getSelectedRow(), 0).toString());
            nomepro_txt.setText(produtos_table.getValueAt(produtos_table.getSelectedRow(), 1).toString());
            preco_txt.setText(produtos_table.getValueAt(produtos_table.getSelectedRow(), 2).toString());
            tipo_txt.setText(produtos_table.getValueAt(produtos_table.getSelectedRow(), 3).toString());
        }
    }//GEN-LAST:event_produtos_tableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Produtos_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Produtos_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Produtos_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Produtos_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Produtos_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_BTN;
    public static javax.swing.JMenuBar barrinha;
    private javax.swing.JButton buscar_BTN;
    private javax.swing.JButton editar_BTN;
    private javax.swing.JButton excluir_BTN;
    public static javax.swing.JTextField id_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton limpar_BTN;
    public static javax.swing.JTextField nomepro_txt;
    public static javax.swing.JTextField preco_txt;
    private javax.swing.JTable produtos_table;
    public static javax.swing.JTextField tipo_txt;
    // End of variables declaration//GEN-END:variables
}
